version: '3.8'

services:
  airflow:
    image: apache/airflow:2.10.0
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "airflow db migrate &&
              airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
              airflow webserver --pid=/opt/airflow/airflow-webserver.pid --daemon &&
              airflow scheduler --daemon"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 10s
      retries: 5